# Generated by Django 3.2.8 on 2021-12-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20211221_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
